app: fiap-exploring-database-options

custom:
  pyIndividually:
    dockerizedPip: true

functions:
  convert-csv-json:
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - smallFilesCsv
              - Arn
    handler: convert-csv-json/lambda_function.lambda_handler
    memorySize: 128
    name: convert-csv-json
    package:
      include:
        - convert-csv-json/**
  read-from-raw-to-sqs:
    events:
      - s3:
        bucket: raw-json
        event: s3:ObjectCreated:*
        existing: true
        rules:
          - suffix: .json
    handler: read-from-raw-to-sqs/lambda_function.lambda_handler
    memorySize: 128
    name: read-from-raw-to-sqs
    package:
      include:
        - read-from-raw-to-sqs/**
  read-from-small-to-sqs:
    events:
      - s3:
        bucket: small-files
        event: s3:ObjectCreated:*
        existing: true
        rules:
          - suffix: .csv
    handler: read-from-small-to-sqs/lambda_function.lambda_handler
    memorySize: 128
    name: read-from-small-to-sqs
    package:
      include:
        - read-from-small-to-sqs/**
  send-raw-json-to-firehose:
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - rawJsonToFirehose
              - Arn
    handler: send-raw-json-to-firehose/lambda_function.lambda_handler
    memorySize: 256
    name: send-raw-json-to-firehose
    package:
      include:
        - send-raw-json-to-firehose/**

package:
  exclude:
    - .editorconfig
    - .github/**
    - node_modules/**
    - sample/**
    - venv/**
    - README.md
  excludeDevDependencies: false
  individually: true

plugins:
  - serverless-plugin-create-deployment-bucket
  - serverless-plugin-existing-s3
  - serverless-python-individually

provider:
  deploymentBucket:
    blockPublicAccess: true
    name: fiap-exploring-database-options-serverless
    serverSideEncryption: AES256
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "firehose:*"
        - "kinesis:*"
        - "s3:*"
        - "sqs:*"
      Resource: "*"
  lambdaHashingVersion: 20201221
  name: aws
  region: us-east-2
  runtime: python3.8
  s3:
    small-files:
      name: small-files
  timeout: 30
  tracing:
    lambda: true

resources:
  Resources:
    curatedAvro:
      Properties:
        BucketName: fiap-exploring-database-options-curated-avro
      Type: AWS::S3::Bucket
    fiapGlueDatabase:
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseInput:
          LocationUri: s3://firehose-ingest/
          Name: fiap
      Type: AWS::Glue::Database
    fiapGlueTableJson:
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseName: fiap
        TableInput:
          Parameters: {
            'classification': 'json'
          }
          StorageDescriptor:
            Columns:
              - Type: bigint
                Name: VendorID
              - Type: string
                Name: tpep_pickup_datetime
              - Type: string
                Name: tpep_dropoff_datetime
              - Type: bigint
                Name: passenger_count
              - Type: decimal
                Name: trip_distance
              - Type: decimal
                Name: pickup_longitude
              - Type: decimal
                Name: pickup_latitude
              - Type: bigint
                Name: RateCodeID
              - Type: string
                Name: store_and_fwd_flag
              - Type: string
                Name: dropoff_longitude
              - Type: string
                Name: dropoff_latitude
              - Type: bigint
                Name: payment_type
              - Type: bigint
                Name: fare_amount
              - Type: bigint
                Name: extra
              - Type: decimal
                Name: mta_tax
              - Type: decimal
                Name: tip_amount
              - Type: decimal
                Name: tolls_amount
              - Type: decimal
                Name: improvement_surcharge
              - Type: decimal
                Name: total_amount
            Location: s3://fiap-exploring-database-options-ingested/json/
          Name: json
          TableType: EXTERNAL_TABLE
      Type: AWS::Glue::Table
    fiapGlueTableParquet:
      Properties:
        CatalogId: !Ref AWS::AccountId
        DatabaseName: fiap
        TableInput:
          Parameters: {
            'classification': 'parquet'
          }
          StorageDescriptor:
            Columns:
              - Type: bigint
                Name: VendorID
              - Type: string
                Name: tpep_pickup_datetime
              - Type: string
                Name: tpep_dropoff_datetime
              - Type: bigint
                Name: passenger_count
              - Type: decimal
                Name: trip_distance
              - Type: decimal
                Name: pickup_longitude
              - Type: decimal
                Name: pickup_latitude
              - Type: bigint
                Name: RateCodeID
              - Type: string
                Name: store_and_fwd_flag
              - Type: string
                Name: dropoff_longitude
              - Type: string
                Name: dropoff_latitude
              - Type: bigint
                Name: payment_type
              - Type: bigint
                Name: fare_amount
              - Type: bigint
                Name: extra
              - Type: decimal
                Name: mta_tax
              - Type: decimal
                Name: tip_amount
              - Type: decimal
                Name: tolls_amount
              - Type: decimal
                Name: improvement_surcharge
              - Type: decimal
                Name: total_amount
            Location: s3://fiap-exploring-database-options-ingested/parquet/
          Name: parquet
          TableType: EXTERNAL_TABLE
      Type: AWS::Glue::Table
    firehoseIngestJson:
      Properties:
        DeliveryStreamName: firehose-ingest-json
        DeliveryStreamType: DirectPut
        ExtendedS3DestinationConfiguration:
          BucketARN:
            Fn::GetAtt:
              - ingested
              - Arn
          BufferingHints:
            IntervalInSeconds: 300
            SizeInMBs: 100
          Prefix: json/
          RoleARN:
            Fn::GetAtt:
              - firehoseIngestRole
              - Arn
      Type: AWS::KinesisFirehose::DeliveryStream
    firehoseIngestParquet:
      Properties:
        DeliveryStreamName: firehose-ingest-parquet
        DeliveryStreamType: DirectPut
        ExtendedS3DestinationConfiguration:
          BucketARN:
            Fn::GetAtt:
              - ingested
              - Arn
          BufferingHints:
            IntervalInSeconds: 300
            SizeInMBs: 100
          DataFormatConversionConfiguration:
            OutputFormatConfiguration:
              Serializer:
                ParquetSerDe:
                  Compression: SNAPPY
            SchemaConfiguration:
              DatabaseName: fiap
              TableName: parquet
          Prefix: parquet/
          RoleARN:
            Fn::GetAtt:
              - firehoseIngestRole
              - Arn
      Type: AWS::KinesisFirehose::DeliveryStream
    firehoseIngestPolicy:
      Properties:
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action:
                - glue:*
                - s3:*
              Resource:
                - '*'
          Version: '2012-10-17'
        PolicyName: firehose-ingest
        Roles:
            - !Ref firehoseIngestRole
      Type: AWS::IAM::Policy
    firehoseIngestRole:
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            - Sid: ''
              Action: sts:AssumeRole
              Effect: Allow
              Principal:
                Service:
                  - firehose.amazonaws.com
                  - glue.amazonaws.com
          Version: '2012-10-17'
      Type: AWS::IAM::Role
    ingested:
      Properties:
        BucketName: fiap-exploring-database-options-ingested
      Type: AWS::S3::Bucket
    rawJson:
      Properties:
        BucketName: fiap-exploring-database-options-raw-json
      Type: AWS::S3::Bucket
    rawJsonToFirehose:
      Properties:
        QueueName: raw-json-to-firehose
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - rawJsonToFirehoseDlq
              - Arn
          maxReceiveCount: 5
      Type: AWS::SQS::Queue
    rawJsonToFirehoseDlq:
      Properties:
        QueueName: raw-json-to-firehose-dlq
      Type: AWS::SQS::Queue
    smallFiles:
      Properties:
        BucketName: fiap-exploring-database-options-small-files
      Type: AWS::S3::Bucket
    smallFilesCsv:
      Properties:
        QueueName: small-files-csv
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - smallFilesCsvDlq
              - Arn
          maxReceiveCount: 5
      Type: AWS::SQS::Queue
    smallFilesCsvDlq:
      Properties:
        QueueName: small-files-csv-dlq
      Type: AWS::SQS::Queue

service: fiap-exploring-database-options
